### ISSUE TITLE
Great generator tool

### ISSUE THREAD

**Issue by theofidry** [audreyfeldroy/favicon-cheat-sheet#50]
I really don't know if it may help but in all case it's really a great favicon generator worth to look at!

http://realfavicongenerator.net/

**Comment by user501254** [comment]
it's still in beta but works well :+1:

**Comment by nofxx** [comment]
I've used this and realfavicon information to build this:
http://github.com/nofxx/yamg
Thanks!

**Comment by TraderStf** [comment]
this one also, free these days
http://appshopper.com/mac/developer-tools/cook-app-icon
Cook App Icon (Developer Tools) Generate icons for iOS, WatchOS, OS X, TVOS and Android apps
